# Generated by Django 4.2.4 on 2023-08-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tiger_park_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiger_park',
            name='clients',
            field=models.TextField(max_length=254),
        ),
    ]
