# Generated by Django 4.2.4 on 2023-08-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_student_contact_alter_student_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='tigerpark',
            name='total_employee',
        ),
    ]
