# Generated by Django 4.2.4 on 2023-08-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_student_age_student_contact_alter_student_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.IntegerField(default=123456789),
        ),
    ]
