# Generated by Django 4.2.4 on 2023-08-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_student_contact_remove_student_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TigerPark',
        ),
    ]
