# Generated by Django 4.2.4 on 2023-08-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_tigerpark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
