# Generated by Django 4.2.4 on 2023-08-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_student_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
