# Generated by Django 4.2.4 on 2023-08-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_student_address_remove_student_contact_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
